# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='reccurrence',
            new_name='times',
        ),
    ]
