# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20170131_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='link',
            field=models.CharField(default='https://www.facebook.com/victor.park.5473', max_length=200),
            preserve_default=False,
        ),
    ]
