# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bill_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='times',
            field=models.IntegerField(),
        ),
    ]
