# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 01:56
from __future__ import unicode_literals

import apps.bills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_bill_payday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True, unique=True, validators=[apps.bills.models.validateLengthGreaterThanTwo, apps.bills.models.validEmail, apps.bills.models.emailcheck]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45, validators=[apps.bills.models.validateLengthGreaterThanTwo, apps.bills.models.validName]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45, validators=[apps.bills.models.validateLengthGreaterThanTwo, apps.bills.models.validName]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[apps.bills.models.passLength]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[apps.bills.models.phonecheck]),
        ),
    ]
